### ISSUE TITLE
Simple matrix multiplication

### ISSUE THREAD

**Issue by laytonjb** [numba/pyculib#13]
I've been trying to write a simple matrix multiplication using pyculib and I'm struggling. I've looked at the test code but wanted something simpler. I grabbed some code from Issue #10 and tried it. The code is,

# 2D Matrix muutplication
import numpy as np
import scipy.linalg.blas as blas
import numba.cuda as cuda
import pyculib.blas as cublas

if __name__ == '__main__':

   A = np.random.randn(3, 3)
   B = np.random.randn(3, 3)

   C = blas.sgemm(1.0, A, B)
   print(C)

   A_d = cuda.to_device(A)
   B_d = cuda.to_device(B)

   C_d = cublas.gemm("N", "N", 1.0, A_d, B_d)

   C_h = np.zeros((3, 3), dtype=np.float64)
   C_d.copy_to_host(C_h)
   print(C_h)

# end if main

When I run it, I get the following errors:

$ python test2.py
[[-0.93004775 -0.37172991  2.20027375]
 [-1.06670713  0.53134644  4.56343937]
 [ 0.37097451  0.42116866 -0.23884274]]
Traceback (most recent call last):
  File "test2.py", line 18, in <module>
    C_d = cublas.gemm("N", "N", 1.0, A_d, B_d)
  File "/home/laytonjb/anaconda2/lib/python2.7/site-packages/pyculib/blas/__init__.py", line 143, in gemm
    colmajor(A, dtype, 'A'), colmajor(B, dtype, 'B'),
  File "/home/laytonjb/anaconda2/lib/python2.7/site-packages/pyculib/nputil.py", line 38, in colmajor
    if not x.flags['F_CONTIGUOUS']:
AttributeError: 'DeviceNDArray' object has no attribute 'flags'

I don't follow the comments in Issue #10 to fix this. Is there a simple way to fix it or a simple matrix multiplication example?

Thanks!

**Comment by stuartarchibald** [comment]
Just tried this with Numba 0.42:
```python
import numpy as np
import scipy.linalg.blas as blas
import numba.cuda as cuda
import pyculib.blas as cublas

A = np.random.randn(3, 3)
B = np.random.randn(3, 3)

C = blas.sgemm(1.0, A, B)
print(C)

A_d = cuda.to_device(A)
B_d = cuda.to_device(B)

C_d = cublas.gemm("N", "N", 1.0, A_d, B_d)
print(C_d)
```
works fine since https://github.com/numba/numba/pull/2667 was merged, closing.
