### ISSUE TITLE
Installation without conda on Windows

### ISSUE THREAD

**Issue by peytondmurray** [numba/pyculib#17]
Hi all,

I'm trying to install pyculib in vanilla python 3.6.4 on Windows without conda, but I'm running into an issue. After installing via `pip install pyculib` and setting environment variables:

| Environment Variable | Value |
| --- | --- |
| NUMBAPRO_CUDALIB | C:\CUDA\v9.1\bin |
| NUMBAPRO_LIBDEVICE | C:\CUDA\v9.1\nvvm\libdevice |
| NUMBAPRO_LVVM | C:\CUDA\v9.1\nvvm\bin\nvvm64_32_0.dll |

Upon `import pyculib`,

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\pyculib\__init__.py", line 49, in <module>
    from . import blas, sparse, fft, rand, sorting
  File "C:\Python36\lib\site-packages\pyculib\sorting\__init__.py", line 1, in <module>
    from .radixsort import RadixSort
  File "C:\Python36\lib\site-packages\pyculib\sorting\radixsort.py", line 38, in <module>
    lib = load_lib('radixsort')
  File "C:\Python36\lib\site-packages\pyculib\sorting\common.py", line 26, in load_lib
    return ctypes.CDLL(libpath)
  File "C:\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

The problem seems to be that upon importing, pyculib tries to find a radixsort library by calling `pyculib.sorting.load_lib()`. `load_lib()` first checks for \<site-packages\>\pyculib\sorting\pyculib_radixsort.dll, which doesn't exist, and then tries to find a radixsort library using `numba.findlib.get_lib_dir()`. `get_lib_dir()` simply checks for \<python install directory\>\DLLs\pyculib_radixsort.dll, which also doesn't exist.

I tried building numba/pyculib_sorting from source, but nvcc claims I have an unsupported GPU architecture, 'compute_20'. I'm running on a GeForce 940M, compute capability 5.0.

Anyone have any ideas?

**Comment by LuisFF** [comment]
Same here.
I tried to re-install pyculib and numba from scratch and then I stumble in yet another problem:

```
[cuda_parallel] C:\Users\a_user\sandbox\pyculib>python runtests.py
E
======================================================================
ERROR: pyculib (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\a_user\sandbox\pyculib\pyculib\__init__.py", line 23, in load_tests
    from .tests import test_cases
  File "C:\Users\a_user\sandbox\pyculib\pyculib\tests\__init__.py", line 2, in <module>
    from . import (test_blas_low_level, test_blas, test_fft, test_rand,
  File "C:\Users\a_user\sandbox\pyculib\pyculib\tests\test_blas_low_level.py", line 4, in <module>
    from .base import CUDATestCase
  File "C:\Users\a_user\sandbox\pyculib\pyculib\tests\base.py", line 20, in <module>
    @skipIf(skip_cuda_tests(), "CUDA not supported on this platform.")
  File "C:\Users\a_user\sandbox\pyculib\pyculib\tests\base.py", line 9, in skip_cuda_tests
    if cuda.is_available():
  File "C:\Users\a_user\AppData\Local\Continuum\Anaconda3\envs\cuda_parallel\lib\site-packages\numba\cuda\device_init.py", line 26, in is_available
    return driver.driver.is_available and nvvm.is_available()
  File "C:\Users\a_user\AppData\Local\Continuum\Anaconda3\envs\cuda_parallel\lib\site-packages\numba\cuda\cudadrv\driver.py", line 254, in is_available
    self.initialize()
  File "C:\Users\a_user\AppData\Local\Continuum\Anaconda3\envs\cuda_parallel\lib\site-packages\numba\cuda\cudadrv\driver.py", line 225, in initialize
    self.cuInit(0)
  File "C:\Users\a_user\AppData\Local\Continuum\Anaconda3\envs\cuda_parallel\lib\site-packages\numba\cuda\cudadrv\driver.py", line 287, in safe_cuda_api_call
    retcode = libfn(*args)
  File "C:\Users\a_user\AppData\Local\Continuum\Anaconda3\envs\cuda_parallel\lib\site-packages\numba\cuda\cudadrv\driver.py", line 307, in absent_function
    raise CudaDriverError(MISSING_FUNCTION_ERRMSG % fname)
numba.cuda.cudadrv.error.CudaDriverError: driver missing function: cuInit.
Requires CUDA 7.5 or above.
```
I am using CUDA driver 9.2, windows 10, anaconda's python 3.5.4.
```NUMBAPRO_CUDA_DRIVER=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\cudart64_92.dll```

I suspect it has to do with some incompatibility with the latest driver version.

**Comment by C2H5OHlife** [comment]
> Same here.
> I tried to re-install pyculib and numba from scratch and then I stumble in yet another problem:
> 
> ```
> [cuda_parallel] C:\Users\a_user\sandbox\pyculib>python runtests.py
> E
> ======================================================================
> ERROR: pyculib (unittest.loader._FailedTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\Users\a_user\sandbox\pyculib\pyculib\__init__.py", line 23, in load_tests
>     from .tests import test_cases
>   File "C:\Users\a_user\sandbox\pyculib\pyculib\tests\__init__.py", line 2, in <module>
>     from . import (test_blas_low_level, test_blas, test_fft, test_rand,
>   File "C:\Users\a_user\sandbox\pyculib\pyculib\tests\test_blas_low_level.py", line 4, in <module>
>     from .base import CUDATestCase
>   File "C:\Users\a_user\sandbox\pyculib\pyculib\tests\base.py", line 20, in <module>
>     @skipIf(skip_cuda_tests(), "CUDA not supported on this platform.")
>   File "C:\Users\a_user\sandbox\pyculib\pyculib\tests\base.py", line 9, in skip_cuda_tests
>     if cuda.is_available():
>   File "C:\Users\a_user\AppData\Local\Continuum\Anaconda3\envs\cuda_parallel\lib\site-packages\numba\cuda\device_init.py", line 26, in is_available
>     return driver.driver.is_available and nvvm.is_available()
>   File "C:\Users\a_user\AppData\Local\Continuum\Anaconda3\envs\cuda_parallel\lib\site-packages\numba\cuda\cudadrv\driver.py", line 254, in is_available
>     self.initialize()
>   File "C:\Users\a_user\AppData\Local\Continuum\Anaconda3\envs\cuda_parallel\lib\site-packages\numba\cuda\cudadrv\driver.py", line 225, in initialize
>     self.cuInit(0)
>   File "C:\Users\a_user\AppData\Local\Continuum\Anaconda3\envs\cuda_parallel\lib\site-packages\numba\cuda\cudadrv\driver.py", line 287, in safe_cuda_api_call
>     retcode = libfn(*args)
>   File "C:\Users\a_user\AppData\Local\Continuum\Anaconda3\envs\cuda_parallel\lib\site-packages\numba\cuda\cudadrv\driver.py", line 307, in absent_function
>     raise CudaDriverError(MISSING_FUNCTION_ERRMSG % fname)
> numba.cuda.cudadrv.error.CudaDriverError: driver missing function: cuInit.
> Requires CUDA 7.5 or above.
> ```
> I am using CUDA driver 9.2, windows 10, anaconda's python 3.5.4.
> `NUMBAPRO_CUDA_DRIVER=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin\cudart64_92.dll`
> 
> I suspect it has to do with some incompatibility with the latest driver version.

hello, have you solved this problem? I got the same error too.

**Comment by peytondmurray** [comment]
pyculib appears to be abandoned in favor of [CuPy](https://github.com/cupy/cupy).

**Comment by C2H5OHlife** [comment]
> pyculib appears to be abandoned in favor of [CuPy](https://github.com/cupy/cupy).

I‘m using numba only, my issue is the same with @LuisFF ’s.
Does numba support cuda 9.0 now?

**Comment by peytondmurray** [comment]
I'm not a numba dev or anything but it [seems like it should work](https://github.com/numba/numba/issues/3327).
