### ISSUE TITLE
CUDA 9 support ?

### ISSUE THREAD

**Issue by jeng1220** [numba/pyculib#18]
Hi,
Is pyculib not support CUDA 9 ?
I run this simple example:
```python
#numba_example2.py
import numpy as np
from pyculib import rand as curand
prng = curand.PRNG(rndtype=curand.PRNG.XORWOW)
rand = np.empty(100000)
prng.uniform(rand)
print(rand[:10])
```
but got following error:
```python
Traceback (most recent call last):
  File "numba_example2.py", line 2, in <module>
    from pyculib import rand as curand
ImportError: cannot import name 'rand'
```
I used `conda install numba cudatoolkit pyculib` to install pyculib and my environment was CUDA 9.

**Comment by stuartarchibald** [comment]
CUDA 7, 8, 9,10 should work fine. What does `numba -s` say in the `CUDA` section?

**Comment by jeng1220** [comment]
After deep dive on it, the root-cause is `pyculib` package from `pip` misses `pyculib_radixsort.so` and `pyculib_segsort.so`. Users have to compile and install [pyculib_sorting](https://github.com/numba/pyculib_sorting) appropriately by themselves.  However, there is no clear document records how to do it. The key is put compiled libraries to installed folder of pyculib, such as :
```bash
ln -s ./lib/pyculib_radixsort.so /usr/local/lib/python3.6/dist-packages/pyculib/sorting/pyculib_radixsort.so
ln -s ./lib/pyculib_segsort.so /usr/local/lib/python3.6/dist-packages/pyculib/sorting/pyculib_segsort.so
```
Could someone help to solve this dependency issue please?

**Comment by stuartarchibald** [comment]
@jeng1220 please note this remark on the `README.rst` for this project:

> NOTE: This project is no longer receiving updates, as we think that CuPy is provides a much more complete interface to standard GPU algorithms. CuPy arrays also work with Numba-compiled GPU kernels now. We encourage you to take a look at CuPy:
  https://cupy.chainer.org/

**Comment by jeng1220** [comment]
@stuartarchibald , thank you for the quick reply. Close this issue.

**Comment by stuartarchibald** [comment]
Thanks, closing.
