### ISSUE TITLE
Getting C pointer of pyculib.blas functions

### ISSUE THREAD

**Issue by vss888** [numba/pyculib#20]
I am trying to see if one can accelerate [statsmodels/tsa/kalmanf/kalman_loglike.pyx](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/kalmanf/kalman_loglike.pyx) by changing running BLAS functions from CPU to GPU.

Please, let me know if there is a way to get C-pointers to pyculib.blas functions in a way similar to how it can be done in scipy, e.g.

``` python
import scipy.linalg.blas
from numpy import float64
scipy.linalg.blas.get_blas_funcs('gemm', dtype=float64)._cpointer
# <capsule object NULL at 0x7f8d22adb300>
```
?

Thank you for your help!

**Comment by stuartarchibald** [comment]
The `pyculib.blas` functions are just grabbing pointer to the `blas` functions in the `cublas` library and using ctypes to do the binding, perhaps look in here for inspiration: https://github.com/numba/pyculib/blob/master/pyculib/blas/binding.py
