### ISSUE TITLE
pyculib.blas.Blas.gemv() returning wrong answers

### ISSUE THREAD

**Issue by zachcristina** [numba/pyculib#21]
pyculib.blas.Blas.gemv() is reshaping input arrays in a strange way, and consequently returning wrong answers. Consider the following example:

```python
import numpy as np
import numba,pyculib

# *** PROBLEM ***

A = np.random.rand(1024,512)
x = np.random.rand(512)

Ag = numba.cuda.to_device(A)
xg = numba.cuda.to_device(x)
yg = numba.cuda.device_array(shape=(1024,), dtype=np.float64)

blOb = pyculib.blas.Blas()

y = np.dot(A,x)

blOb.gemv('N',1024,512,1,Ag,xg,0,yg)

print np.allclose(y,yg.copy_to_host())

# *** WORKAROUND ***

A = np.random.rand(1024,512)
x = np.random.rand(512)

B = np.reshape(np.transpose(A),A.shape)

Bg = numba.cuda.to_device(B)
xg = numba.cuda.to_device(x)
yg = numba.cuda.device_array(shape=(1024,), dtype=np.float64)

blOb = pyculib.blas.Blas()

y = np.dot(A,x)

blOb.gemv('N',1024,512,1,Bg,xg,0,yg)

print np.allclose(y,yg.copy_to_host())
```

When I run these, the first example always returns `False` and the second always returns `True`. This suggests that the BLAS routine is transposing the input matrix, then reshaping it to fit the appropriate shape. Playing around with the `'N'` argument in the BLAS kernel doesn't seem to help. My workaround, while straightforward enough, requires arrays in GPU memory to be copied to host for reshaping and then returned to GPU memory, which is rather slow!

Has anybody had any similar problems?

**Comment by mdessole** [comment]
Hi,
I had the same problem and I solved it by passing the matrix as a Fortran array. Using your code, I call gemv in the following way:
`blOb.gemv('N',1024,512,1,np.asfortranarray(Ag),xg,0,yg)`
However, I don't get why it does't work without this trick...

**Comment by mdessole** [comment]
Hi, 
I had a similar problem. I solved it by passing the matrix as a Fortran array. In your example:
`
# *** PROBLEM ***

A = np.random.rand(1024,512)
x = np.random.rand(512)

A = np.asfortranarray(A)

Ag = numba.cuda.to_device(A)
xg = numba.cuda.to_device(x)
yg = numba.cuda.device_array(shape=(1024,), dtype=np.float64)

blOb = pyculib.blas.Blas()

y = np.dot(A,x)

blOb.gemv('N',1024,512,1,Ag,xg,0,yg)

print(np.allclose(y,yg.copy_to_host()))

`
This way it works.

**Comment by stuartarchibald** [comment]
@mdessole thanks for responding, that BLAS expects on Fortran ordered arrays is seemingly root cause of the issue.

**Comment by zachcristina** [comment]
Great, fixed! Thanks very much for your help.
